services:
  - type: web
    name: lancre-saas
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PORT
        value: 8000
